name: "Omega Zirkel Discord Plugin"
main: de.omegazirkel.risingworld.DiscordWebHook
version: 0.8.3
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "This Plugin can be used to display ingame chat in a Discord channel"
license: EMS
website: coming soon